# Generated by Django 6.0.5 on 2026-06-15 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_representante', models.BooleanField(default=False)),
                ('es_estudiante', models.BooleanField(default=False)),
                ('es_cantina', models.BooleanField(default=False)),
                ('tipo', models.CharField(blank=True, choices=[('DOCENTE', 'Docente'), ('ADMIN', 'Administrativo'), ('REPRESENTANTE', 'Representante'), ('ESTUDIANTE', 'Estudiante'), ('CANTINA', 'Personal de Cantina')], max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BilleteraCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='billetera_cantina', to='users.persona')),
            ],
            options={
                'verbose_name': 'Billetera Cantina',
                'verbose_name_plural': 'Billeteras Cantina',
            },
        ),
        migrations.CreateModel(
            name='RecargaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Número de Tx o captura', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='users.billeteracantina')),
                ('registrado_por', models.ForeignKey(help_text='Cantinero que recibió el dinero', limit_choices_to={'es_cantina': True}, on_delete=django.db.models.deletion.PROTECT, related_name='recargas_procesadas', to='users.persona')),
                ('representante', models.ForeignKey(help_text='Quién realiza el aporte', limit_choices_to={'es_representante': True}, on_delete=django.db.models.deletion.PROTECT, to='users.persona')),
            ],
            options={
                'verbose_name': 'Recarga de Billetera',
                'verbose_name_plural': 'Recargas de Billeteras',
            },
        ),
        migrations.CreateModel(
            name='RelacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(limit_choices_to={'tipo': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='users.persona')),
                ('representante', models.ForeignKey(limit_choices_to={'tipo': 'REPRESENTANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='representados', to='users.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('can_manage_news', models.BooleanField(default=False, verbose_name='Gestionar Noticias')),
                ('can_manage_gallery', models.BooleanField(default=False, verbose_name='Gestionar Galería')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='Gestionar Personal')),
                ('can_manage_students', models.BooleanField(default=False, verbose_name='Gestionar Alumnos/Reps')),
                ('can_manage_grades', models.BooleanField(default=False, verbose_name='Gestionar Calificaciones')),
                ('can_manage_finances', models.BooleanField(default=False, verbose_name='Gestionar Cobros/Pagos')),
                ('can_manage_canteen', models.BooleanField(default=False, verbose_name='Gestionar Cantina')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rol'),
        ),
        migrations.CreateModel(
            name='RubroCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: PASTELES, REFRESCOS, CHUCHERIAS', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_cantina', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Rubro de Cantina',
                'verbose_name_plural': 'Rubros de Cantina',
            },
        ),
        migrations.CreateModel(
            name='VentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='users.billeteracantina')),
                ('registrado_por', models.ForeignKey(limit_choices_to={'es_cantina': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_procesadas', to='users.persona')),
            ],
            options={
                'verbose_name': 'Consumo en Cantina',
                'verbose_name_plural': 'Consumos en Cantina',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio fijado en el momento', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rubrocantina')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.ventacantina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rubrocantina',
            constraint=models.UniqueConstraint(fields=('colegio', 'nombre'), name='unique_rubro_por_colegio'),
        ),
    ]
