# Generated by Django 4.2.30 on 2026-04-26 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('DOCENTE', 'Docente'), ('ADMIN', 'Administrativo'), ('REPRESENTANTE', 'Representante'), ('ESTUDIANTE', 'Estudiante'), ('CANTINA', 'Personal de Cantina')], max_length=20)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
