# Generated by Django 4.2.30 on 2026-05-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_persona_activo_alter_persona_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(limit_choices_to={'tipo': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='users.persona')),
                ('representante', models.ForeignKey(limit_choices_to={'tipo': 'REPRESENTANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='representados', to='users.persona')),
            ],
        ),
    ]
