# Generated by Django 4.2.30 on 2026-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_relacionfamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_cantina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_representante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(blank=True, choices=[('DOCENTE', 'Docente'), ('ADMIN', 'Administrativo'), ('REPRESENTANTE', 'Representante'), ('ESTUDIANTE', 'Estudiante'), ('CANTINA', 'Personal de Cantina')], max_length=20, null=True),
        ),
    ]
