# Generated by Django 4.2.30 on 2026-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_persona_es_admin_persona_es_cantina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/'),
        ),
    ]
