# Generated by Django 6.0.5 on 2026-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_persona_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
