# Generated by Django 6.0.5 on 2026-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_persona_especialidad_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
