# Generated by Django 6.0.5 on 2026-06-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0003_colegio_tiene_cantina'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='billetera_cantina', to='users.persona')),
            ],
            options={
                'verbose_name': 'Billetera Cantina',
                'verbose_name_plural': 'Billeteras Cantina',
            },
        ),
        migrations.CreateModel(
            name='RecargaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Número de Tx o captura', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='users.billeteracantina')),
                ('registrado_por', models.ForeignKey(help_text='Cantinero que recibió el dinero', limit_choices_to={'es_cantina': True}, on_delete=django.db.models.deletion.PROTECT, related_name='recargas_procesadas', to='users.persona')),
                ('representante', models.ForeignKey(help_text='Quién realiza el aporte', limit_choices_to={'es_representante': True}, on_delete=django.db.models.deletion.PROTECT, to='users.persona')),
            ],
            options={
                'verbose_name': 'Recarga de Billetera',
                'verbose_name_plural': 'Recargas de Billeteras',
            },
        ),
        migrations.CreateModel(
            name='RubroCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: PASTELES, REFRESCOS, CHUCHERIAS', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_cantina', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Rubro de Cantina',
                'verbose_name_plural': 'Rubros de Cantina',
            },
        ),
        migrations.CreateModel(
            name='VentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='users.billeteracantina')),
                ('registrado_por', models.ForeignKey(limit_choices_to={'es_cantina': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_procesadas', to='users.persona')),
            ],
            options={
                'verbose_name': 'Consumo en Cantina',
                'verbose_name_plural': 'Consumos en Cantina',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaCantina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio fijado en el momento', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rubrocantina')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='users.ventacantina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rubrocantina',
            constraint=models.UniqueConstraint(fields=('colegio', 'nombre'), name='unique_rubro_por_colegio'),
        ),
    ]
