# Generated by Django 4.2.30 on 2026-05-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0003_colegio_tiene_cantina'),
        ('users', '0006_persona_es_admin_persona_es_cantina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_especialidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=3)),
                ('capacidad', models.PositiveIntegerField(default=35)),
                ('etapa', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA', 'Media')], max_length=20)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
                ('docente_guia', models.ForeignKey(blank=True, limit_choices_to={'es_docente': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.persona')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academico.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.IntegerField(choices=[(1, '1er Lapso'), (2, '2do Lapso'), (3, '3er Lapso')])),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('valor_cualitativo', models.CharField(blank=True, max_length=2, null=True)),
                ('descripcion_pedagogica', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(choices=[('INI', 'Educación Inicial'), ('PRI', 'Educación Primaria'), ('MGE', 'Media General'), ('MTE', 'Media Técnica')], max_length=3)),
                ('es_cuantitativo', models.BooleanField(default=False)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='academico.niveleducativo'),
        ),
        migrations.CreateModel(
            name='EstudianteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('becado', models.BooleanField(default=False)),
                ('porcentaje_beca', models.IntegerField(default=0)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_academico', to='users.persona')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=1)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('asistente_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.persona')),
                ('asistente_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistente_2', to='users.persona')),
                ('docente_interino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_suplente', to='users.persona')),
                ('docente_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_titular', to='users.persona')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academico.grado'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('costo_mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('GRADUADO', 'Graduado')], default='ACTIVO', max_length=15)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.anioescolar')),
                ('estudiante', models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='users.persona')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.seccion')),
            ],
            options={
                'unique_together': {('estudiante', 'anio_escolar')},
            },
        ),
    ]
