# Generated by Django 6.0.5 on 2026-06-15 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('matricula1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matricula2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('matricula3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mensualidad1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mensualidad2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mensualidad3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ej: MAT-1G, CAS-3G', max_length=20, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA_GENERAL', 'Media General'), ('MEDIA_TECNICA', 'Media Técnica')], max_length=20)),
                ('grado', models.CharField(max_length=35)),
                ('horas_semanales', models.PositiveIntegerField(default=2, help_text='Carga horaria de la materia')),
                ('es_area_desarrollo', models.BooleanField(default=False, verbose_name='Es Área de Desarrollo (Inicial)')),
                ('es_especialidad', models.BooleanField(default=False, verbose_name='Es Especialidad (Inglés/Música/Deporte)')),
                ('es_tecnica', models.BooleanField(default=False, verbose_name='Es Materia Técnica/Especializada')),
                ('mencion', models.CharField(blank=True, help_text='Ej: Informática, Comercio (Solo para Media Técnica)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
            },
        ),
        migrations.CreateModel(
            name='DocenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('becado', models.BooleanField(default=False)),
                ('porcentaje_beca', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InformeCualitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('descriptor', models.CharField(blank=True, choices=[('I', 'Iniciado (I)'), ('EP', 'En Proceso (EP)'), ('C', 'Consolidado (C)')], max_length=3, null=True)),
                ('informe_descriptivo', models.TextField(blank=True, help_text='Descripción pedagógica del rendimiento, avances o rasgos de personalidad', null=True)),
                ('observaciones_recomendaciones', models.TextField(blank=True, help_text='Sugerencias para el representante', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informe Cualitativo',
                'verbose_name_plural': 'Informes Cualitativos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('costo_mensualidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('GRADUADO', 'Graduado')], default='ACTIVO', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCualitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('calificacion', models.CharField(choices=[('I', 'Iniciado (I)'), ('EP', 'En Proceso (EP)'), ('C', 'Consolidado (C)')], help_text='Iniciado (I), En Proceso (EP) o Consolidado (C)', max_length=2)),
                ('observacion', models.TextField(blank=True, help_text='Apreciación pedagógica del docente', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Cualitativa',
                'verbose_name_plural': 'Notas Cualitativas',
            },
        ),
        migrations.CreateModel(
            name='NotaCuantitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Cuantitativa',
                'verbose_name_plural': 'Notas Cuantitativas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('matricula', 'Matrícula'), ('mensualidad', 'Mensualidad'), ('extraordinario', 'Pago Extraordinario')], default='mensualidad', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la cuota', max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo en Divisas'), ('efectivo_bs', 'Efectivo en Bs'), ('zelle', 'Zelle'), ('punto', 'Punto de Venta')], default='transferencia', max_length=25, null=True)),
                ('num_referencia', models.CharField(blank=True, help_text='Número de referencia bancaria o recibo', max_length=100, null=True)),
                ('monto_bs', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en Bolívares que deposito el representante', max_digits=15, null=True)),
                ('banco', models.CharField(blank=True, choices=[('venezuela', 'VENEZUELA'), ('provincial', 'PROVINCIAL'), ('mercantil', 'MERCANTIL'), ('banesco', 'BANESCO'), ('sofitasa', 'SOFITASA'), ('caribe', 'BANCO CARIBE'), ('exterior', 'BANCO EXTERIOR'), ('tesoro', 'BANCO DEL TESORO'), ('bvc', 'BANCO VENEZOLANO DE CRÉDITO'), ('caroni', 'BANCO CARONÍ'), ('plaza', 'BANCO PLAZA'), ('bangente', 'BANCO BANGENTE'), ('bfc', 'BANCO FONDO COMÚN'), ('del_sur', 'BANCO DEL SUR'), ('100banco', '100% BANCO'), ('bancrecer', 'BANCRECER'), ('activo', 'BANCO ACTIVO'), ('bancamiga', 'BANCAMIGA'), ('banplus', 'BANPLUS'), ('bfa', 'BCO FUERZA ARMADA NAC BOL'), ('bnc', 'BANCO NAC DE CRÉDITO'), ('otro', 'OTRO')], help_text='Banco desde el cual se realizó el pago', max_length=50, null=True)),
                ('titular_cuenta', models.CharField(blank=True, help_text='Nombre del titular de la cuenta desde la que se realizó el pago', max_length=100, null=True)),
                ('num_cuota', models.CharField(help_text="Ej: 'UNICA' para matrícula/especiales, o del '1' al '12' para mensualidades", max_length=25)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del pago', null=True)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en la que el representante realizó/se validó el pago', null=True)),
                ('detalle', models.TextField(blank=True, help_text='Concepto. Ej: Mensualidad Octubre', null=True)),
                ('pagado', models.BooleanField(default=False, help_text='Indica si el pago ya fue procesado y verificado')),
                ('comprobante', models.ImageField(blank=True, help_text='Captura o foto del comprobante', null=True, upload_to='pagos/comprobantes/%Y/%m/')),
                ('activo', models.BooleanField(default=True, help_text='Falso significa que el pago fue anulado/borrado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo de anulación o corrección, si aplica', null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('descripcion', models.CharField(help_text='Ej: Taller, Examen, Trabajo Práctico', max_length=100)),
                ('ponderacion', models.PositiveIntegerField(help_text='Porcentaje de la nota total del lapso (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=3)),
                ('capacidad', models.PositiveIntegerField(default=35)),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA_GENERAL', 'Media General'), ('MEDIA_TECNICA', 'Media Técnica')], max_length=20)),
                ('es_cuantitativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_actualizacion'],
            },
        ),
    ]
