# Generated by Django 4.2.30 on 2026-05-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantedetalle',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
