# Generated by Django 6.0.5 on 2026-06-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('colegios', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativodetalle',
            name='administrativo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_laboral', to='users.persona'),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_asignaturas', to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_asignadas', to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_docente', to='users.persona'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='docente_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_auxiliar', to='users.persona'),
        ),
        migrations.AddField(
            model_name='docentedetalle',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_docente', to='users.persona'),
        ),
        migrations.AddField(
            model_name='estudiantedetalle',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_academico', to='users.persona'),
        ),
        migrations.AddField(
            model_name='informecualitativo',
            name='carga_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_cualitativos', to='academico.cargaacademica'),
        ),
        migrations.AddField(
            model_name='informecualitativo',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='informes_cualitativos', to='users.persona'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.anioescolar'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='users.persona'),
        ),
        migrations.AddField(
            model_name='notacualitativa',
            name='carga_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_cualitativas', to='academico.cargaacademica'),
        ),
        migrations.AddField(
            model_name='notacualitativa',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_cualitativas', to='users.persona'),
        ),
        migrations.AddField(
            model_name='notacuantitativa',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_cuantitativas', to='users.persona'),
        ),
        migrations.AddField(
            model_name='pago',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='academico.anioescolar'),
        ),
        migrations.AddField(
            model_name='pago',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='users.persona'),
        ),
        migrations.AddField(
            model_name='pago',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó o anuló el pago, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planevaluacion',
            name='carga_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='academico.cargaacademica'),
        ),
        migrations.AddField(
            model_name='notacuantitativa',
            name='plan_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudiantes', to='academico.planevaluacion'),
        ),
        migrations.AddField(
            model_name='representantedetalle',
            name='representante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_representante', to='users.persona'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.anioescolar'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='docente_guia',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_guiadas', to='users.persona'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.seccion'),
        ),
        migrations.AddField(
            model_name='estudiantedetalle',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.seccion'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='tasacambio',
            unique_together={('moneda', 'fecha')},
        ),
        migrations.AddConstraint(
            model_name='informecualitativo',
            constraint=models.UniqueConstraint(fields=('estudiante', 'carga_academica', 'lapso'), name='unique_informe_por_lapso'),
        ),
        migrations.AddConstraint(
            model_name='notacualitativa',
            constraint=models.UniqueConstraint(fields=('estudiante', 'carga_academica', 'lapso'), name='unique_nota_cualitativa_por_lapso'),
        ),
        migrations.AddConstraint(
            model_name='notacuantitativa',
            constraint=models.UniqueConstraint(fields=('estudiante', 'plan_evaluacion'), name='unique_nota_por_actividad'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('colegio', 'anio_escolar', 'grado', 'nombre'), name='unique_seccion_por_periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'anio_escolar')},
        ),
        migrations.AddConstraint(
            model_name='cargaacademica',
            constraint=models.UniqueConstraint(fields=('seccion', 'asignatura'), name='unique_materia_por_seccion'),
        ),
    ]
