# Generated by Django 6.0.5 on 2026-05-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_estudiantedetalle_fecha_nacimiento'),
        ('users', '0007_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('profesion', models.CharField(max_length=100)),
                ('administrativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_laboral', to='users.persona')),
            ],
        ),
    ]
