# Generated by Django 6.0.5 on 2026-06-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='es_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='usuario_edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_editadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
