# Generated by Django 6.0.5 on 2026-05-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_administrativodetalle'),
        ('users', '0007_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_docente', to='users.persona')),
            ],
        ),
    ]
