# Generated by Django 6.0.5 on 2026-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_tasacambio_es_manual_tasacambio_usuario_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='es_estimado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
