# Generated by Django 6.0.5 on 2026-05-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_docentedetalle'),
        ('users', '0008_remove_persona_especialidad_persona_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('representante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_representante', to='users.persona')),
            ],
        ),
    ]
