# Generated by Django 6.0.5 on 2026-05-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_representante'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativodetalle',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='docentedetalle',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='estudiantedetalle',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='matricula1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='matricula2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='matricula3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='mensualidad1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='mensualidad2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anioescolar',
            name='mensualidad3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='costo_matricula',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='costo_mensualidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RepresentanteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_representante', to='users.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
