# Generated by Django 6.0.5 on 2026-05-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_remove_administrativodetalle_profesion_and_more'),
        ('colegios', '0003_colegio_tiene_cantina'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioescolar',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio'),
            preserve_default=False,
        ),
    ]
