# Generated by Django 6.0.5 on 2026-05-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_anioescolar_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='etapa',
        ),
        migrations.AddField(
            model_name='seccion',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA General', 'Media General'), ('MEDIA Técnica', 'Media Técnica')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
