# Generated by Django 6.0.5 on 2026-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_remove_seccion_etapa_seccion_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='es_cuantitativo',
            field=models.BooleanField(default=False),
        ),
    ]
