# Generated by Django 6.0.5 on 2026-05-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_seccion_es_cuantitativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargaacademica',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='asistente_1',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='asistente_2',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='docente_interino',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='docente_principal',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='seccion',
            name='grado',
            field=models.CharField(max_length=35),
        ),
        migrations.RemoveField(
            model_name='niveleducativo',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='CargaAcademica',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='NivelEducativo',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
