# Generated by Django 6.0.5 on 2026-05-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_remove_cargaacademica_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='anio_escolar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academico.anioescolar'),
            preserve_default=False,
        ),
    ]
