# Generated by Django 6.0.5 on 2026-06-01 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_seccion_anio_escolar'),
        ('colegios', '0003_colegio_tiene_cantina'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total pagado', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo en Divisas'), ('efectivo_bs', 'Efectivo en Bs'), ('zelle', 'Zelle'), ('punto', 'Punto de Venta')], default='transferencia', max_length=25)),
                ('num_referencia', models.CharField(blank=True, help_text='Número de referencia bancaria o recibo', max_length=100, null=True)),
                ('fecha_pago', models.DateField(help_text='Fecha en la que el representante realizó el pago')),
                ('detalle', models.TextField(blank=True, help_text='Concepto. Ej: Mensualidad Octubre y Noviembre', null=True)),
                ('comprobante', models.ImageField(blank=True, help_text='Captura o foto del comprobante', null=True, upload_to='pagos/comprobantes/%Y/%m/')),
                ('activo', models.BooleanField(default=True, help_text='Falso significa que el pago fue anulado/borrado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se registró en el sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='academico.anioescolar')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='colegios.colegio')),
                ('estudiante', models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='users.persona')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-id'],
            },
        ),
    ]
