# Generated by Django 6.0.5 on 2026-06-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='num_cuota',
            field=models.PositiveIntegerField(default=1, help_text='Número de cuota que se está pagando. Ej: 1 para la primera mensualidad, 2 para la segunda, etc.'),
            preserve_default=False,
        ),
    ]
