# Generated by Django 6.0.5 on 2026-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_pago_num_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_pagado',
            field=models.BooleanField(default=False, help_text='Indica si el pago ha sido verificado y registrado oficialmente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='num_cuota',
            field=models.PositiveIntegerField(help_text='Número de cuota que se está pagando. Ej: 1 para la primera mensualidad, 2 para la segunda, etc. y unica para matricula y pagos especiales'),
        ),
    ]
