# Generated by Django 6.0.5 on 2026-06-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_pago_es_pagado_alter_pago_num_cuota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='es_pagado',
            new_name='pagado',
        ),
    ]
