# Generated by Django 6.0.5 on 2026-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_rename_es_pagado_pago_pagado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['fecha_vencimiento', 'id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del pago', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('matricula', 'Matrícula'), ('mensualidad', 'Mensualidad'), ('extraordinario', 'Pago Extraordinario')], default='mensualidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='detalle',
            field=models.TextField(blank=True, help_text='Concepto. Ej: Mensualidad Octubre', null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en la que el representante realizó/se validó el pago', null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('efectivo', 'Efectivo en Divisas'), ('efectivo_bs', 'Efectivo en Bs'), ('zelle', 'Zelle'), ('punto', 'Punto de Venta')], default='transferencia', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto de la cuota', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='num_cuota',
            field=models.CharField(help_text="Ej: 'UNICA' para matrícula/especiales, o del '1' al '12' para mensualidades", max_length=25),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Indica si el pago ya fue procesado y verificado'),
        ),
    ]
