# Generated by Django 6.0.5 on 2026-06-02 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_pago_options_pago_fecha_vencimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo de anulación o corrección, si aplica', null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó o anuló el pago, si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
