# Generated by Django 6.0.5 on 2026-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_pago_motivo_pago_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_actualizacion'],
                'unique_together': {('moneda', 'fecha')},
            },
        ),
    ]
