# Generated by Django 6.0.5 on 2026-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_tasacambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_bs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en Bolívares que deposito el representante', max_digits=15, null=True),
        ),
    ]
