# Generated by Django 6.0.5 on 2026-06-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_pago_monto_bs'),
        ('colegios', '0003_colegio_tiene_cantina'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ej: MAT-1G, CAS-3G', max_length=20, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA General', 'Media General'), ('MEDIA Técnica', 'Media Técnica')], max_length=20)),
                ('grado', models.CharField(max_length=35)),
                ('horas_semanales', models.PositiveIntegerField(default=2, help_text='Carga horaria de la materia')),
                ('es_area_desarrollo', models.BooleanField(default=False, verbose_name='Es Área de Desarrollo (Inicial)')),
                ('es_especialidad', models.BooleanField(default=False, verbose_name='Es Especialidad (Inglés/Música/Deporte)')),
                ('es_tecnica', models.BooleanField(default=False, verbose_name='Es Materia Técnica/Especializada')),
                ('mencion', models.CharField(blank=True, help_text='Ej: Informática, Comercio (Solo para Media Técnica)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_asignaturas', to='colegios.colegio')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_asignadas', to='academico.asignatura')),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_docente', to='users.persona')),
                ('docente_auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_auxiliar', to='users.persona')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.seccion')),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
                'unique_together': {('seccion', 'asignatura')},
            },
        ),
    ]
