# Generated by Django 6.0.5 on 2026-06-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_asignatura_cargaacademica'),
        ('colegios', '0003_colegio_tiene_cantina'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterUniqueTogether(
            name='cargaacademica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA_GENERAL', 'Media General'), ('MEDIA_TECNICA', 'Media Técnica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='docente_guia',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_guiadas', to='users.persona'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('MEDIA_GENERAL', 'Media General'), ('MEDIA_TECNICA', 'Media Técnica')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cargaacademica',
            constraint=models.UniqueConstraint(fields=('seccion', 'asignatura'), name='unique_materia_por_seccion'),
        ),
        migrations.AddConstraint(
            model_name='seccion',
            constraint=models.UniqueConstraint(fields=('colegio', 'anio_escolar', 'grado', 'nombre'), name='unique_seccion_por_periodo'),
        ),
    ]
