# Generated by Django 6.0.5 on 2026-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_alter_seccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, choices=[('VENEZUELA', 'VENEZUELA'), ('PROVINCIAL', 'PROVINCIAL'), ('MERCANTIL', 'MERCANTIL'), ('BANESCO', 'BANESCO'), ('SOFITASA', 'SOFITASA'), ('BANCO CARIBE', 'BANCO CARIBE'), ('BANCO EXTERIOR', 'BANCO EXTERIOR'), ('BANCO DEL TESORO', 'BANCO DEL TESORO'), ('BANCO VENEZOLANO DE CRÉDITO', 'BANCO VENEZOLANO DE CRÉDITO'), ('BANCO CARONÍ', 'BANCO CARONÍ'), ('BANCO PLAZA', 'BANCO PLAZA'), ('BANCO BANGENTE', 'BANCO BANGENTE'), ('BANCO FONDO COMÚN', 'BANCO FONDO COMÚN'), ('BANCO DEL SUR', 'BANCO DEL SUR'), ('100% BANCO', '100% BANCO'), ('BANCRECER', 'BANCRECER'), ('BANCO ACTIVO', 'BANCO ACTIVO'), ('BANCAMIGA', 'BANCAMIGA'), ('BANPLUS', 'BANPLUS'), ('BCO FUERZA ARMADA NAC BOL', 'BCO FUERZA ARMADA NAC BOL'), ('BANCO NAC DE CREDITO', 'BANCO NAC DE CRÉDITO'), ('OTRO', 'OTRO')], help_text='Banco desde el cual se realizó el pago', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='titular_cuenta',
            field=models.CharField(blank=True, help_text='Nombre del titular de la cuenta desde la que se realizó el pago', max_length=100, null=True),
        ),
    ]
