# Generated by Django 6.0.5 on 2026-06-07 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_pago_banco_pago_titular_cuenta'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, choices=[('venezuela', 'VENEZUELA'), ('provincial', 'PROVINCIAL'), ('mercantil', 'MERCANTIL'), ('banesco', 'BANESCO'), ('sofitasa', 'SOFITASA'), ('caribe', 'BANCO CARIBE'), ('exterior', 'BANCO EXTERIOR'), ('tesoro', 'BANCO DEL TESORO'), ('bvc', 'BANCO VENEZOLANO DE CRÉDITO'), ('caroni', 'BANCO CARONÍ'), ('plaza', 'BANCO PLAZA'), ('bangente', 'BANCO BANGENTE'), ('bfc', 'BANCO FONDO COMÚN'), ('del_sur', 'BANCO DEL SUR'), ('100banco', '100% BANCO'), ('bancrecer', 'BANCRECER'), ('activo', 'BANCO ACTIVO'), ('bancamiga', 'BANCAMIGA'), ('banplus', 'BANPLUS'), ('bfa', 'BCO FUERZA ARMADA NAC BOL'), ('bnc', 'BANCO NAC DE CRÉDITO'), ('otro', 'OTRO')], help_text='Banco desde el cual se realizó el pago', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('descripcion', models.CharField(help_text='Ej: Taller, Examen, Trabajo Práctico', max_length=100)),
                ('ponderacion', models.PositiveIntegerField(help_text='Porcentaje de la nota total del lapso (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='academico.cargaacademica')),
            ],
        ),
        migrations.CreateModel(
            name='InformeCualitativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('descriptor', models.CharField(blank=True, choices=[('I', 'Iniciado (I)'), ('EP', 'En Proceso (EP)'), ('C', 'Consolidado (C)')], max_length=3, null=True)),
                ('informe_descriptivo', models.TextField(blank=True, help_text='Descripción pedagógica del rendimiento, avances o rasgos de personalidad', null=True)),
                ('observaciones_recomendaciones', models.TextField(blank=True, help_text='Sugerencias para el representante', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_cualitativos', to='academico.cargaacademica')),
                ('estudiante', models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='informes_cualitativos', to='users.persona')),
            ],
            options={
                'verbose_name': 'Informe Cualitativo',
                'verbose_name_plural': 'Informes Cualitativos',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'carga_academica', 'lapso'), name='unique_informe_por_lapso')],
            },
        ),
        migrations.CreateModel(
            name='NotaCuantitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_cuantitativas', to='users.persona')),
                ('plan_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_estudiantes', to='academico.planevaluacion')),
            ],
            options={
                'verbose_name': 'Nota Cuantitativa',
                'verbose_name_plural': 'Notas Cuantitativas',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'plan_evaluacion'), name='unique_nota_por_actividad')],
            },
        ),
    ]
