# Generated by Django 6.0.5 on 2026-06-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_alter_pago_banco_planevaluacion_informecualitativo_and_more'),
        ('users', '0009_persona_fecha_nacimiento_persona_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCualitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.CharField(choices=[('1', '1er Lapso (Sep-Dic)'), ('2', '2do Lapso (Ene-Mar)'), ('3', '3er Lapso (Abr-Jul)')], max_length=2)),
                ('calificacion', models.CharField(choices=[('I', 'Iniciado (I)'), ('EP', 'En Proceso (EP)'), ('C', 'Consolidado (C)')], help_text='Iniciado (I), En Proceso (EP) o Consolidado (C)', max_length=2)),
                ('observacion', models.TextField(blank=True, help_text='Apreciación pedagógica del docente', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_cualitativas', to='academico.cargaacademica')),
                ('estudiante', models.ForeignKey(limit_choices_to={'es_estudiante': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notas_cualitativas', to='users.persona')),
            ],
            options={
                'verbose_name': 'Nota Cualitativa',
                'verbose_name_plural': 'Notas Cualitativas',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'carga_academica', 'lapso'), name='unique_nota_cualitativa_por_lapso')],
            },
        ),
    ]
