"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7h$-3+w0k_tmmy&63epb&mh-lc!-3p)!of26h=b#3xhy0cx26'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  
    'django.contrib.staticfiles',    
    'cloudinary',          
    'users',
    'web',
    'colegios',
    'academico.apps.AcademicoConfig',  # Única y apuntando a la configuración de señales
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'siscolegio_db',       # El nombre de la base de datos que creaste en MariaDB
        'USER': 'root',            # Tu usuario de MariaDB
        'PASSWORD': 'root', # Tu contraseña de MariaDB
        'HOST': '127.0.0.1',       # O 'localhost'
        'PORT': '3307',            # Puerto por defecto
        'OPTIONS': {
            'use_pure': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Esta es la línea clave que le dice a Django dónde buscar carpetas 'static' manuales
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# (Opcional) Donde se juntarán todos al final
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.Usuario'# Agrega esta línea para usar tu modelo de usuario personalizado


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Configuración de Cloudinary
import dj_database_url

# =====================================================================
# CONFIGURACIÓN DINÁMICA ENTORNO LOCAL / PRODUCCIÓN (RENDER)
# =====================================================================

# 1. Seguridad
SECRET_KEY = os.environ.get('SECRET_KEY', 'clave-secreta-local-de-emergencia-123')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# 2. Base de Datos Inteligente
DATABASES = {
    'default': dj_database_url.config(
        # REEMPLAZA EL TEXTO DE ABAJO con los datos reales de tu MariaDB local actual
        default='mysql://root:root@127.0.0.1:3307/siscolegio_db',
        conn_max_age=600
    )
}

# 3. Archivos Estáticos (WhiteNoise)
STATIC_URL = 'static/'
WHITENOISE_MANIFEST_STRICT = False
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Estructura unificada para Django moderno
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.ManifestStaticFilesStorage",
    },
}

# Línea de compatibilidad requerida por django-cloudinary-storage en Django 6.x
STATICFILES_STORAGE = "whitenoise.storage.ManifestStaticFilesStorage"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'dozrhfngb'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '861756927926695'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'vIxCvpekrNGTquLrSTy1RjK_mXA'),
}



