"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv 

# Carga las variables del archivo .env justo al iniciar
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7h$-3+w0k_tmmy&63epb&mh-lc!-3p)!of26h=b#3xhy0cx26'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'cloudinary_storage',     
    'cloudinary',          
    'users',
    'web',
    'colegios',
    'academico.apps.AcademicoConfig',  # Única y apuntando a la configuración de señales
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    # CONFIGURACIÓN PARA PRODUCCIÓN (Neon / PostgreSQL)
    # dj-database-url detecta automáticamente el formato 'postgres://...'
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True  # Neon requiere conexión segura
        )
    }
else:
    # 💻 TU CONFIGURACIÓN LOCAL (Tu PC con MariaDB)
    DATABASES = {
        'default': {
            'ENGINE': 'mysql.connector.django',
            'NAME': 'siscolegio_db',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': '127.0.0.1',
            'PORT': '3307',
            'OPTIONS': {
                'use_pure': True,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True


# =====================================================================
# CONFIGURACIÓN DE ENTORNO EN PRODUCCIÓN (RENDER)
# =====================================================================

# 1. Seguridad e Infraestructura
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-f7h$-3+w0k_tmmy&63epb&mh-lc!-3p)!of26h=b#3xhy0cx26')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# =====================================================================
# CONFIGURACIÓN DE SEGURIDAD EXCLUSIVA PARA PRODUCCIÓN (RENDER)
# =====================================================================
if not DEBUG:
    # Le dice a Django que confíe en el proxy HTTPS de Render
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Dominios de confianza para permitir peticiones POST (Seguridad CSRF)
    CSRF_TRUSTED_ORIGINS = [
        'https://sistemacolegio.onrender.com',
    ]
    
    # (Opcional recomendado) Fuerza el uso de HTTPS en las cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# 2. Archivos Estáticos (WhiteNoise)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
WHITENOISE_MANIFEST_STRICT = False

# 3. Archivos Multimedia y Almacenamiento (Cloudinary)
MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.Usuario'

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

# Línea de compatibilidad requerida por django-cloudinary-storage en Django 6.x
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
