from django.urls import path
from django.contrib.auth import views as auth_views
from django.shortcuts import render, get_object_or_404
from .views import ColegioLoginView, dashboard_colegio
from . import views # Importamos las vistas desde el archivo views.py del mismo directorio

urlpatterns = [
    path('<slug:colegio_slug>/login/', ColegioLoginView.as_view(), name='login_colegio'),
    path('<slug:colegio_slug>/logout/', views.logout_colegio, name='logout_colegio'),
    path('<slug:colegio_slug>/dashboard/', dashboard_colegio, name='dashboard_colegio'),
    path('<slug:colegio_slug>/crear-publicacion/', views.crear_publicacion, name='crear_publicacion'),
    path('<slug:colegio_slug>/dashboard/cargar-galeria/', views.cargar_galeria, name='cargar_galeria'),
    path('<slug:colegio_slug>/dashboard/gestionar/', views.gestionar_contenido, name='gestionar_contenido'),
    path('<slug:colegio_slug>/dashboard/eliminar-pub/<int:pub_id>/', views.eliminar_publicacion, name='eliminar_publicacion'),
    path('<slug:colegio_slug>/dashboard/editar-pub/<int:pub_id>/', views.editar_publicacion, name='editar_publicacion'),
    path('<slug:colegio_slug>/dashboard/eliminar-img/<int:img_id>/', views.eliminar_imagen, name='eliminar_imagen'),
    path('<slug:colegio_slug>/dashboard/usuarios/nuevo/', views.crear_usuario_colegio, name='crear_usuario'),
    path('<slug:colegio_slug>/seguridad/usuarios/', views.gestionar_usuarios, name='gestionar_usuarios'),
    path('<slug:colegio_slug>/seguridad/roles/', views.gestionar_roles, name='gestionar_roles'),
    path('<slug:colegio_slug>/seguridad/roles/nuevo/', views.crear_rol, name='crear_rol'),    
    path('usuario/estado/<int:usuario_id>/', views.alternar_estado_usuario, name='alternar_estado_usuario'),
    path('usuario/reset-password/<int:usuario_id>/', views.resetear_password_usuario, name='resetear_password'), 
    path('usuarios/cambiar-rol/<int:usuario_id>/', views.cambiar_rol_usuario, name='cambiar_rol_usuario'),   
    # GESTIÓN DE DOCENTES
    path('<slug:colegio_slug>/docente/', views.dashboard_docente, name='dashboard_docente'),
    path('<slug:colegio_slug>/docente/ver-curso/<int:asignacion_id>/', views.ver_curso_docente, name='ver_curso_docente'),
    path('<slug:colegio_slug>/personas/docentes/', views.gestionar_docentes, name='gestionar_docentes'),
    path('<slug:colegio_slug>/personas/docentes/crear/', views.crear_docente, name='crear_docente'),
    path('<slug:colegio_slug>/personas/docentes/editar/<int:persona_id>/', views.editar_docente, name='editar_docente'),
    path('<slug:colegio_slug>/personas/docentes/reactivar/<int:persona_id>/', views.reactivar_docente, name='reactivar_docente'),
    path('<slug:colegio_slug>/personas/docentes/eliminar/<int:persona_id>/', views.eliminar_docente, name='eliminar_docente'),
    path('<slug:colegio_slug>/personas/docentes/carga-masiva/', views.cargar_docentes_excel, name='cargar_docentes_excel'),
    path('<slug:colegio_slug>/descargar-plantilla-docentes/', views.descargar_plantilla_docentes, name='descargar_plantilla_docentes'),
    path('<slug:colegio_slug>/personas/docentes/ficha-pdf/<int:docente_id>/', views.imprimir_ficha_docente, name='imprimir_ficha_docente'),
    path('<slug:colegio_slug>/personas/docentes/cargar-excel/', views.cargar_docentes_excel, name='cargar_docentes_excel'),
    path('<slug:colegio_slug>/docentes/exportar/excel/', views.exportar_docentes_xls, name='exportar_docentes_xls'),
    path('<slug:colegio_slug>/docentes/exportar/pdf/', views.exportar_docentes_pdf, name='exportar_docentes_pdf'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/', views.ver_curso_docente, name='ver_curso_docente'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/plan/', views.gestionar_plan_evaluacion, name='gestionar_plan_evaluacion'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/evaluar/<int:plan_id>/', views.cargar_notas_actividad, name='cargar_notas_actividad'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/reporte-final/', views.reporte_final_curso, name='reporte_final_curso'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/importar-plantilla/', views.importar_plantilla_excel, name='importar_plantilla_excel'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/exportar-plantilla/', views.exportar_plantilla_excel, name='exportar_plantilla_excel'),
    # Ruta para el docente (mantiene el comportamiento actual)
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/ver-boleta/<int:estudiante_id>/', views.ver_boleta_estudiante, name='ver_boleta_estudiante'),
    # Ruta para ver boleta general (sin asignacion_id)
    path('<slug:colegio_slug>/ver-boleta-general/<int:estudiante_id>/', views.ver_boleta_estudiante, name='ver_boleta_general'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/reporte-final/<int:estudiante_id>/', views.reporte_final_curso, name='reporte_final_curso'),
    path('<slug:colegio_slug>/docente/curso/<int:asignacion_id>/imprimir-todas/', views.imprimir_todas_boletas, name='imprimir_todas_boletas'),
    # GESTIÓN DE ADMINISTRATIVOS
    path('<slug:colegio_slug>/personas/administrativos/', views.gestionar_administrativos, name='gestionar_administrativos'),
    path('<slug:colegio_slug>/personas/administrativos/crear/', views.crear_administrativo, name='crear_administrativo'),
    path('<slug:colegio_slug>/personas/administrativos/editar/<int:persona_id>/', views.editar_administrativo, name='editar_administrativo'),
    path('<slug:colegio_slug>/personas/administrativos/eliminar/<int:persona_id>/', views.eliminar_administrativo, name='eliminar_administrativo'),
    path('<slug:colegio_slug>/personas/administrativos/reactivar/<int:persona_id>/', views.reactivar_administrativo, name='reactivar_administrativo'),
    path('<slug:colegio_slug>/personas/administrativos/ficha-pdf/<int:administrativo_id>/', views.imprimir_ficha_administrativo, name='imprimir_ficha_administrativo'),
    path('<slug:colegio_slug>/personas/administrativos/cargar-excel/', views.cargar_administrativos_excel, name='cargar_administrativos_excel'),
    path('<slug:colegio_slug>/personas/administrativos/descargar-plantilla/', views.descargar_plantilla_admin, name='descargar_plantilla_admin'),
    path('<slug:colegio_slug>/administrativos/exportar/excel/', views.exportar_administrativos_xls, name='exportar_administrativos_xls'),
    path('<slug:colegio_slug>/administrativos/exportar/pdf/', views.exportar_administrativos_pdf, name='exportar_administrativos_pdf'),
    # GESTIÓN DE ESTUDIANTES
    path('<slug:colegio_slug>/personas/estudiantes/', views.gestionar_estudiantes, name='gestionar_estudiantes'),
    path('<slug:colegio_slug>/personas/estudiante/crear/', views.crear_estudiante_completo, name='crear_estudiante'),
    # path('<slug:colegio_slug>/personas/estudiantes/ficha/<int:estudiante_id>/', views.ficha_estudiante, name='ficha_estudiante'),
    path('<slug:colegio_slug>/personas/estudiantes/editar/<int:estudiante_id>/', views.editar_estudiante, name='editar_estudiante'),
    path('<slug:colegio_slug>/personas/estudiantes/desactivar/<int:estudiante_id>/', views.desactivar_estudiante, name='desactivar_estudiante'),
    path('<slug:colegio_slug>/personas/estudiantes/activar/<int:persona_id>/', views.activar_estudiante, name='activar_estudiante'),
    path('<slug:colegio_slug>/personas/estudiantes/imprimir-ficha/<int:estudiante_id>/', views.imprimir_ficha_estudiante_pdf, name='imprimir_ficha_estudiante'),
    path('<slug:colegio_slug>/personas/ficha-modal/<int:estudiante_id>/', views.ficha_estudiante_modal, name='ficha_estudiante_modal'),
    path('<slug:colegio_slug>/personas/estudiantes/excel/', views.exportar_estudiantes_excel, name='exportar_estudiantes_excel'),
    path('<slug:colegio_slug>/personas/estudiantes/pdf/', views.exportar_estudiantes_pdf, name='exportar_estudiantes_pdf'),
    path('<slug:colegio_slug>/personas/estudiantes/descargar-plantilla/', views.descargar_plantilla_estudiantes, name='descargar_plantilla_estudiantes'),
    path('<slug:colegio_slug>/personas/estudiantes/carga-masiva/', views.procesar_carga_masiva_estudiantes, name='procesar_carga_masiva_estudiantes'),
    # GESTIÓN DE REPRESENTANTES
    path('<slug:colegio_slug>/personas/representantes/', views.gestionar_representantes, name='gestionar_representantes'),
    path('<slug:colegio_slug>/personas/representantes/crear/', views.crear_representante, name='crear_representante'),
    path('<slug:colegio_slug>/personas/representantes/verificar-cedula/', views.verificar_cedula_representante, name='verificar_cedula_representante'),
    path('<slug:colegio_slug>/personas/representantes/editar/<int:persona_id>/', views.editar_representante, name='editar_representante'),
    path('<slug:colegio_slug>/personas/representantes/<int:pk>/ficha-modal/', views.ficha_representante_modal, name='ficha_representante_modal'),
    path('<slug:colegio_slug>/personas/representantes/<int:pk>/imprimir/', views.imprimir_ficha_representante_pdf, name='imprimir_ficha_representante_pdf'),
    path('<slug:colegio_slug>/personas/representantes/reactivar/<int:persona_id>/', views.reactivar_representante, name='reactivar_representante'),
    path('<slug:colegio_slug>/personas/representantes/eliminar/<int:persona_id>/', views.eliminar_representante, name='eliminar_representante'),
    path('<slug:colegio_slug>/personas/representantes/carga-masiva/', views.cargar_masiva_representantes, name='cargar_masiva_representantes'),
    path('<slug:colegio_slug>/personas/representantes/descargar-plantilla/', views.descargar_plantilla_representantes, name='descargar_plantilla_representantes'),
    path('<slug:colegio_slug>/personas/representantes/excel/', views.exportar_representantes_excel, name='exportar_representantes_excel'),
    path('<slug:colegio_slug>/personas/representantes/pdf/', views.exportar_representantes_pdf, name='exportar_representantes_pdf'),
    path('<slug:colegio_slug>/personas/representantes/boleta/<int:estudiante_id>/', views.descargar_boleta_representante, name='descargar_boleta_representante'),
    #GESTION CANTINA
    path('<slug:colegio_slug>/cantina/', views.dashboard_cantina, name='dashboard_cantina'),
    path('<slug:colegio_slug>/cantina/registrar-consumo/', views.registrar_consumo_view, name='registrar_consumo'),
    path('<slug:colegio_slug>/cantina/guardar-rubro/', views.guardar_rubro_cantina_view, name='guardar_rubro_cantina'),
    path('<slug:colegio_slug>/estudiante/<int:estudiante_id>/cantina/', views.cantina_estudiante_view, name='cantina_estudiante'),
    #GESTION DE PERIODO ESCOLAR
    path('<slug:colegio_slug>/periodo-escolar/', views.gestionar_anio_escolar, name='gestionar_anio_escolar'),
    path('<slug:colegio_slug>/periodo-escolar/<int:anio_id>/editar/', views.editar_anio_escolar, name='editar_anio_escolar'),
    path('<slug:colegio_slug>/periodo-escolar/<int:anio_id>/cambiar-estado/', views.cambiar_estado_anio, name='cambiar_estado_anio'),
    path('<slug:colegio_slug>/periodo-escolar/exportar-pdf/', views.exportar_anios_escolares_pdf, name='exportar_anios_escolares_pdf'),
    path('<slug:colegio_slug>/asignatura/', views.gestionar_asignaturas, name='gestionar_asignaturas'),
    path('<slug:colegio_slug>/asignatura/exportar-pdf/', views.exportar_asignaturas_pdf, name='exportar_asignaturas_pdf'),
    path('<slug:colegio_slug>/secciones/', views.gestionar_secciones, name='gestionar_secciones'),    
    path('<slug:colegio_slug>/secciones/<int:seccion_id>/docentes/', views.asignar_docentes_seccion, name='asignar_docentes_seccion'),
    path('<slug:colegio_slug>/secciones/<int:seccion_id>/editar/', views.editar_seccion, name='editar_seccion'),
    path('<slug:colegio_slug>/secciones/<int:seccion_id>/eliminar/', views.eliminar_seccion, name='eliminar_seccion'),
    path('<slug:colegio_slug>/secciones/imprimir-listados-pdf/', views.imprimir_listados_pdf, name='imprimir_listados_pdf'),
    path('<slug:colegio_slug>/secciones/<int:seccion_id>/calificaciones/', views.ver_calificaciones_seccion, name='ver_calificaciones_seccion'),
    path('<slug:colegio_slug>/admin/estudiante/<int:estudiante_id>/boleta/', views.imprimir_boleta_admin, name='imprimir_boleta_admin'),
    path('<slug:colegio_slug>/inscripciones/', views.gestionar_inscripciones, name='gestionar_inscripciones'),
    path('<slug:colegio_slug>/inscripciones/<int:estudiante_id>/nueva/', views.crear_inscripcion, name='crear_inscripcion'),
    path('<slug:colegio_slug>/pagos/', views.gestionar_pagos, name='gestionar_pagos'),    
    path('<slug:colegio_slug>/pagos/pagar/', views.realizar_pago, name='realizar_pago'),
    path('<slug:colegio_slug>/pagos/obtener-tasa/', views.obtener_tasa_ajax, name='obtener_tasa_ajax'),
    path('<slug:colegio_slug>/pagos/alumno/<int:estudiante_id>/', views.estado_cuenta_estudiante, name='estado_cuenta_estudiante'),
    path('<slug:colegio_slug>/estudiante/<int:estudiante_id>/pago/<int:pago_id>/editar/', views.editar_pago, name='editar_pago'),
    path('<slug:colegio_slug>/estudiante/<int:estudiante_id>/auditar-accion/', views.auditar_accion_pago, name='auditar_accion_pago'),
    path('<slug:colegio_slug>/pago/<int:pago_id>/imprimir/', views.imprimir_recibo, name='imprimir_recibo'),
    # Ruta para ver la bandeja de entrada de pagos
    path('<slug:colegio_slug>/finanzas/conciliacion/', views.panel_verificar_pagos, name='panel_verificar_pagos'),
    # Ruta invisible que procesa las acciones del formulario (Aprobar/Rechazar)
    path('<slug:colegio_slug>/finanzas/conciliacion/<int:pago_id>/procesar/', views.procesar_verificacion_pago, name='procesar_verificacion_pago'),

    path('<slug:colegio_slug>/personas/subir-foto/<int:persona_id>/', views.subir_foto_persona, name='subir_foto_persona'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('<slug:colegio_slug>/buscar-representante-ajx/', views.buscar_representante_ajx, name='buscar_representante_ajx'),
    path('<slug:colegio_slug>/personas/representantes/buscar-ajax/', views.buscar_representante_ajax_editar_estudiante, name='buscar_representante_ajax_editar_estudiante'),
    path('<slug:colegio_slug>/buscar-estudiante-ajx/', views.buscar_estudiante_ajx, name='buscar_estudiante_ajx'),
    path('<slug:colegio_slug>/tasa-dolar/', views.historico_tasa_cambio, name='tasa_cambio_historico'),
]