# Generated by Django 4.2.30 on 2026-04-25 22:57

import colegios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),                
                ('favicon', models.ImageField(upload_to=colegios.models.ruta_favicon_colegio)),
                ('logo', models.ImageField(upload_to=colegios.models.ruta_logo_colegio)),
                ('informacion_publica', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to=colegios.models.ruta_portada_colegio)),
                ('lema', models.CharField(blank=True, max_length=200, null=True)),
                ('color_principal', models.CharField(default='#1a4731', max_length=7)),
                ('color_secundario', models.CharField(default='#c4a13d', max_length=7)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='publicaciones/')),
                ('tipo', models.CharField(choices=[('EVENTO', 'Evento Próximo'), ('NOTICIA', 'Noticia/Blog')], default='NOTICIA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='colegios.colegio')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='colegios.colegio')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de la Galería',
            },
        ),
    ]
