# Generated by Django 4.2.30 on 2026-04-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='imparte_inicial',
            field=models.BooleanField(default=False, verbose_name='Nivel Inicial'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='imparte_primaria',
            field=models.BooleanField(default=False, verbose_name='Nivel Primaria'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='imparte_secundaria',
            field=models.BooleanField(default=False, verbose_name='Nivel Secundaria'),
        ),
    ]
