# Generated by Django 4.2.30 on 2026-04-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_colegio_imparte_inicial_colegio_imparte_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='tiene_cantina',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Módulo de Cantina?'),
        ),
    ]
