# Generated by Django 6.0.5 on 2026-06-13 16:48

import colegios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0003_colegio_tiene_cantina'),
    ]

    operations = []
