# Generated by Django 6.0.5 on 2026-06-13 19:22

import colegios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0005_alter_colegio_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to=colegios.models.ruta_portada_colegio),
        ),
    ]
