# Generated by Django 6.0.5 on 2026-06-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0006_alter_colegio_imagen_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='informacion_publica',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
