# Generated by Django 6.0.5 on 2026-06-13 22:53

import colegios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0007_remove_colegio_informacion_publica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=colegios.models.ruta_logo_colegio),
        ),
        migrations.AlterField(
            model_name='imagengaleria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
