# Generated by Django 6.0.5 on 2026-06-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0004_alter_colegio_favicon bkp'),
        ('colegios', '0008_alter_colegio_logo_alter_imagengaleria_imagen'),
    ]

    operations = [
    ]
