# Generated by Django 6.0.5 on 2026-06-14 18:00

import colegios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0010_auto_20260614_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=colegios.models.ruta_favicon_colegio),
        ),
    ]
